//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageToDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile
    {
        public int Id { get; set; }
        public byte[] screenshot { get; set; }
    }
}
